# Generated by Django 5.0.1 on 2024-02-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
