# Generated by Django 4.2.4 on 2024-03-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0002_locations_lat_locations_lng_locations_place_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='address',
            new_name='adress',
        ),
    ]
