# Generated by Django 5.0.1 on 2024-03-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0003_rename_address_locations_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='club',
        ),
    ]
