# Generated by Django 5.0.1 on 2024-04-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0004_remove_locations_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='adress',
            new_name='address',
        ),
    ]
