# Generated by Django 5.0.1 on 2024-05-10 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0008_destinationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationrequest',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_content.locations'),
        ),
    ]
